### ISSUE TITLE
Source name resolution bug

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/mmoda-frontend-module#301]
We have a recurrent bug: the name resolver fails and we get an "unknown object" message. It can be a remote service on which we rely failing, but this became really often recently. May be something wrong on the frontend side?

<img width="673" alt="Image" src="https://github.com/user-attachments/assets/ec01a01d-f78b-4531-87b1-0680522ac301" />

**Comment by burnout87** [comment]
Can you please re-try?

This bug was (supposedly) fixed with #298 .

I just tried locally and in production , and:

![Image](https://github.com/user-attachments/assets/402b1304-ad10-44a5-9147-87a291c161d7)

or if a not-existing source:

![Image](https://github.com/user-attachments/assets/3c4541d4-f8e1-4992-9695-5e45d4535746)

It must be said, that it's a bit slow, something I don't experience locally.

**Comment by burnout87** [comment]
And also, I should add that in order to re-enable the Resolve button, you just have to start typing in the input bar

**Comment by dsavchenko** [comment]
I think, the point of Andrii is that `NGC 1068` is a known source, and it was not resolved for him. And this happens regularly. Maybe, we need to re-do request or have some additional fallback with simbad frontend-side.
Also, do we have sentry reporting in the resolver? It may help to understand why resolution fails sometimes.
